name: seq-to-first-iso
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - pyteomics
  - matplotlib
  - pandas
  - pycodestyle
  - pydocstyle
  - pylint
  - twine
  - bumpversion
  - pytest
  - pytest-cov
