name: seq-to-first-iso-readthedocs
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pyteomics
  - pandas
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - pip:
    - nbsphinx-link
    - recommonmark

