name: seq-to-first-iso
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pyteomics
  - matplotlib
  - pandas
  - jupyterlab
  - pycodestyle
  - pydocstyle
  - pylint
  - twine
  - bioconda-utils
  - bumpversion
  - pytest
  - pytest-cov
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - pip:
    - nbsphinx-link
    - recommonmark

