name: seq-to-first-iso-knime
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - pyteomics
  - matplotlib
  - pandas=0.23
  - seq-to-first-iso
